name: GitHub Actions Demo
on:
  repository_dispatch:
    types: [content]

jobs:
  commit_content:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.client_payload.event }}
      - run: echo ${{ github.event.client_payload.model }}
